sudo: required
dist: trusty

language: cpp

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

env:
    global:
        # Intel Parallel Studio
        - secure: "olXtIXnlLfWRsAaINIkArbnNKfDc81Yn2mFg7K4MoX7DVa2m+36qmgYcSWGIiki38nqaByz2PM+QQL/CaSZTNzDYKQ87bGDE8mc1dhexXhdWWRS+jc1hEfWArX4iOCyWDZ+8be/R4AWjuRjaeGzAfkpBi0zzU5vALPBJlvTLRPSvEQibTF2+lQpc3fKyiL9+JFwkKPSdxzLhXDE9GttNgr1RhbUK2WEA2VTSJ3/y5AYY2zqDGDbOJx3L6PCwC0T6mX/B0cNxtm0k2K/9RVmDPS7CKC77pS9L4/2Pq9/JvTzBeJ+cbI8xHexrEoNVrS8t7zJYaB9Tz8iRRh+MgjYqKHbgOBIdlcchBa5BZozfodUzb2lk1/er3NmWN7hEr0se2luGKTrFILYpPLrW3bI9xSI5fonLRafYJEujZo2kzUcOyVRD/5JPFBTIMcjSvY2tfH/Yusb6sVm6W0IBJepzp61h/MwfdaCcAA3tIucnLtEQGSKUyXd7ZU7ObgeUKkqw7mwBcoykUeWDDdlI+72+sjiJiUE18OYWPkYSumzLEKf5qFWpgFXe6hxoWSHZXs5vY1pontXAz2cSeCjffqonaT8JNnXsKCVAxG0ChiEv6AJU8PiiJmLCKNh8Oj3nHbdS7iB9W5+BSLDN0ovNqHSqUezsVaaPFI8z5EML0PpNwBY="
        - COV_FLAGS='-pg -fprofile-arcs -ftest-coverage'

matrix:
    exclude:
        - os: osx
          compiler: gcc
    include:
        - os: linux
          compiler: icc
          env: INTEL_COMPILER=true
        - os: linux
          compiler: gcc
          env: COVERAGE=true

install:
    - if [[ -n "${INTEL_COMPILER}" ]]; then git clone https://github.com/nemequ/icc-travis.git; ./icc-travis/install-icc.sh; fi
    - if [[ -n "${COVERAGE}" ]]; then sudo pip install cpp-coveralls; fi

before_script:
    - if [[ -n "${INTEL_COMPILER}" ]]; then export CC=icc; export CXX=icpc; source ~/.bashrc; fi
    - if [[ -n "${COVERAGE}" ]]; then export CFLAGS=$COV_FLAGS; export CXXFLAGS=$COV_FLAGS; fi

script:
    - ./configure --enable-obj
    - make -j 2
    - make check

after_script:
    - if [[ -n  "${COVERAGE}" ]]; then coveralls > /dev/null; fi
